import unittest
from employee_bonus import BonusCalculator
from test.TestUtils import TestUtils
class ExceptionalTest(unittest.TestCase):
    def test_value_error_for_id(self):
        test_obj = TestUtils()
        try:
            BonusCalculator.calculate_bonus({"id":"101","dob":"1999-4-2"},{"id":101,"salary":8000})
            test_obj.yakshaAssert("TestValueErrorForId",False, "exception")
            print("TestValueErrorForId = Failed")
        except ValueError:
            test_obj.yakshaAssert("TestValueErrorForId", True, "exception")
            print("TestValueErrorForId = Passed")

    def test_value_error_for_salary(self):
        test_obj = TestUtils()
        try:
            BonusCalculator.calculate_bonus({"id":101,"dob":"1999-4-2"},{"id":101,"salary":"8000"})
            test_obj.yakshaAssert("TestValueErrorForSalary",False, "exception")
            print("TestValueErrorForSalary = Failed")
        except ValueError:
            test_obj.yakshaAssert("TestValueErrorForSalary", True, "exception")
            print("TestValueErrorForSalary = Passed")

    def test_value_error_for_dob(self):
        test_obj = TestUtils()
        try:
            BonusCalculator.calculate_bonus({"id":101,"dob":1999-4-2},{"id":101,"salary":8000})
            test_obj.yakshaAssert("TestValueErrorForDob",False, "exception")
            print("TestValueErrorForDob = Failed")
        except ValueError:
            test_obj.yakshaAssert("TestValueErrorForDob", True, "exception")
            print("TestValueErrorForDob = Passed")
